# Generated by Django 4.2.7 on 2023-12-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns1', models.CharField(max_length=255)),
                ('columns2', models.CharField(max_length=255)),
                ('columns3', models.CharField(max_length=255)),
                ('columns4', models.CharField(max_length=255)),
                ('columns5', models.CharField(max_length=255)),
                ('columns6', models.CharField(max_length=255)),
                ('columns7', models.CharField(max_length=255)),
                ('columns8', models.CharField(max_length=255)),
                ('columns9', models.CharField(max_length=255)),
                ('columns10', models.CharField(max_length=255)),
                ('columns11', models.CharField(max_length=255)),
                ('columns12', models.CharField(max_length=255)),
                ('columns13', models.CharField(max_length=255)),
                ('columns14', models.CharField(max_length=255)),
                ('columns15', models.CharField(max_length=255)),
                ('columns16', models.CharField(max_length=255)),
                ('columns17', models.CharField(max_length=255)),
            ],
        ),
    ]
