# Generated by Django 4.2.7 on 2023-12-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('column_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='ModalData',
        ),
        migrations.AddField(
            model_name='dynamicdata',
            name='dynamic_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.dynamicmodel'),
        ),
    ]
